export const data = [
  {
    id: 1,
    marca: "lsc toys",
    produto: "pote pop mini 500ml - branco",
    código_barras: 7908364101254,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 2,
    marca: "lsc toys",
    produto: "pote pop mini 500ml - azul escuro",
    código_barras: 7908364101285,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 3,
    marca: "lsc toys",
    produto: "pote pop mini 500ml - verde flúor",
    código_barras: 7908364101353,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 4,
    marca: "lsc toys",
    produto: "pote pop mini 500ml - rosa ",
    código_barras: 7908364101308,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 5,
    marca: "lsc toys",
    produto: "pote pop mini 500ml - verde",
    código_barras: 7908364101322,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 6,
    marca: "lsc toys",
    produto: "pote pop mini 500ml - preto",
    código_barras: 7908364101315,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 7,
    marca: "lsc toys",
    produto: "balde de pipoca 1L - rosa chiclete",
    código_barras: 7892050501650,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 8,
    marca: "lsc toys",
    produto: "balde de pipoca 1L - rosa",
    código_barras: 7892050501643,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 9,
    marca: "lsc toys",
    produto: "balde de pipoca 1L - amarelo",
    código_barras: 7892050501629,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 10,
    marca: "lsc toys",
    produto: "balde de pipoca 1L - verde",
    código_barras: 7892050501612,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 11,
    marca: "lsc toys",
    produto: "balde de pipoca 1L - azul escuro",
    código_barras: 7892050501599,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 12,
    marca: "lsc toys",
    produto: "balde de pipoca 1L - roxo",
    código_barras: 7892050501636,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 13,
    marca: "lsc toys",
    produto: "balde de pipoca 1L - branco",
    código_barras: 7892050501575,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 14,
    marca: "lsc toys",
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 15,
    marca: "lsc toys",
    produto: "balde de pipoca 1L - preto",
    código_barras: 7892050501568,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 16,
    marca: "lsc toys",
    produto: "balde de pipoca 1L - branco",
    código_barras: 7892050501582,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 17,
    marca: "lsc toys",
    produto: "balde de pipoca 1L - azul claro",
    código_barras: 7892050501605,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 18,
    marca: "lsc toys",
    produto: "balde de pipoca 1L - vermelho",
    código_barras: 7892050501650,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 19,
    marca: "lsc toys",
    produto: "balde de pipoca 2,4L - azul claro",
    código_barras: 7892050501483,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 20,
    marca: "lsc toys",
    produto: "balde de pipoca 2,4L - rosa",
    código_barras: 7892050501520,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 21,
    marca: "lsc toys",
    produto: "balde de pipoca 2,4L - branco",
    código_barras: 7892050501452,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 22,
    marca: "lsc toys",
    produto: "balde de pipoca 2,4L - preto",
    código_barras: 7892050501445,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 23,
    marca: "lsc toys",
    produto: "balde de pipoca 2,4L - amarelo",
    código_barras: 7892050501506,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 24,
    marca: "lsc toys",
    produto: "balde de pipoca 2,4L - roxo",
    código_barras: 7892050501513,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 25,
    marca: "lsc toys",
    produto: "balde de pipoca 2,4L - amarelo",
    código_barras: 7892050501490,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 26,
    marca: "lsc toys",
    produto: "balde de pipoca 2,4L - azul escuro",
    código_barras: 7892050501476,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 27,
    marca: "lsc toys",
    produto: "balde de pipoca 2,4L - vermelho",
    código_barras: 7892050501469,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 28,
    marca: "copomais",
    produto: "prato 15 raso",
    código_barras: 7897147500110,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 29,
    marca: "copomais",
    produto: "tampa 500 tsf sem furo - branco",
    código_barras: 7897147500677,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 30,
    marca: "copomais",
    produto: "tampa 100 tsf sem furo - branco",
    código_barras: 7897147500769,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 31,
    marca: "copomais",
    produto: "copo 50 ml - branco",
    código_barras: 7897147500172,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
  {
    id: 32,
    marca: "copomais",
    produto: "copo 50 ml - transparente",
    código_barras: 7897147500301,
    endereço: "a1",
    est: "true",
    gal: "true",
  },
];
